# Use the official Python image from the Docker Hub as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container's /app directory
COPY requirements.txt .

# Install the dependencies from the requirements.txt file
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of application's code to the container's /app directory
COPY . .

# Expose the port the application will run on (useful if it has a web interface)
# EXPOSE 5000  # Uncomment if  exposing a web service

# Set environment variables if needed (timezone)
ENV TZ=Asia/Taipei

# Command to run the application
CMD ["python", "main.py"]

# Install PyInstaller to build an executable
RUN pip install pyinstaller

# Create an executable from the main.py
RUN pyinstaller --onefile main.py

# Run the executable instead of Python script
CMD ["./dist/main"]
